name: tf212_py310
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.3.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - anyio=4.7.0
  - aom=3.9.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - attr=2.5.1
  - attrs=25.3.0
  - babel=2.16.0
  - beautifulsoup4=4.13.4
  - blas=2.134
  - blas-devel=3.9.0
  - bleach=6.2.0
  - blinker=1.9.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.12.0
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charls=2.4.2
  - charset-normalizer=3.4.3
  - click=8.2.1
  - comm=0.2.1
  - contourpy=1.3.2
  - cryptography=45.0.6
  - cycler=0.12.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - flatbuffers=23.5.26
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - freetype=2.13.3
  - frozenlist=1.7.0
  - gast=0.4.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - glib=2.84.3
  - glib-tools=2.84.3
  - google-auth=2.40.3
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - grpcio=1.54.3
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=9.0.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - imagecodecs=2024.1.1
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.20.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jxrlib=1.1
  - keras-preprocessing=1.1.2
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.19
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgrpc=1.54.3
  - libiconv=1.18
  - libjpeg-turbo=3.1.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.50
  - libpq=16.9
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lz4-c=1.9.4
  - markdown=3.8.2
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mistune=3.1.2
  - mpg123=1.32.9
  - multidict=6.6.3
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.114
  - numpy-base=1.26.4
  - oauthlib=3.3.1
  - openblas=0.3.30
  - openjpeg=2.5.2
  - openssl=3.5.2
  - opt_einsum=3.4.0
  - overrides=7.4.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.45
  - pexpect=4.9.0
  - pillow=10.3.0
  - pixman=0.46.4
  - platformdirs=4.3.7
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyopenssl=22.0.0
  - pyparsing=3.2.3
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=25.2.10
  - python-json-logger=3.2.1
  - python_abi=3.10
  - pyu2f=0.1.5
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.8
  - rav1e=0.7.1
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.4
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - rsa=4.9.1
  - scikit-image=0.25.0
  - scikit-learn=1.7.1
  - send2trash=1.8.2
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.2.0
  - svt-av1=3.0.2
  - tensorboard=2.15.2
  - tensorboard-data-server=0.7.0
  - tensorflow=2.15.0
  - tensorflow-base=2.15.0
  - tensorflow-estimator=2.15.0
  - termcolor=3.1.0
  - terminado=0.17.1
  - threadpoolctl=3.6.0
  - tifffile=2024.12.12
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - array-record==0.7.2
      - dm-tree==0.1.9
      - docstring-parser==0.17.0
      - efficientnet==1.0.0
      - einops==0.8.1
      - etils==1.13.0
      - fsspec==2025.7.0
      - h5py==3.10.0
      - image-classifiers==1.0.0
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - kagglehub==0.3.12
      - keras==2.15.0
      - keras-applications==1.0.8
      - keras-core==0.1.7
      - keras-cv==0.9.0
      - keras-unet-collection==0.1.13
      - markdown-it-py==4.0.0
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - namex==0.1.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pandas==2.3.1
      - patchify==0.2.3
      - pip==24.3.1
      - promise==2.3
      - protobuf==4.21.12
      - pyarrow==21.0.0
      - pytz==2025.2
      - regex==2025.7.34
      - rich==14.1.0
      - scipy==1.11.4
      - segmentation-models==1.0.1
      - setuptools==80.9.0
      - simple-parsing==0.1.7
      - tensorflow-datasets==4.9.9
      - tensorflow-metadata==1.17.2
      - tqdm==4.67.1
      - tzdata==2025.2
      - wrapt==1.14.1
prefix: /home/anvy4548/anaconda3/envs/tf212_py310
